// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLCoK5Ws9HXpYgNItiuEml3OgfvwygjwQ',
    appId: '1:236974689896:web:da7b2299161f72788cf5dd',
    messagingSenderId: '236974689896',
    projectId: 'product-mate',
    authDomain: 'product-mate.firebaseapp.com',
    storageBucket: 'product-mate.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBas-EMuwdX3LGi_YPI4LoIb3PUMcHljwI',
    appId: '1:236974689896:android:eed7f4625fc90c108cf5dd',
    messagingSenderId: '236974689896',
    projectId: 'product-mate',
    storageBucket: 'product-mate.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMsqKIgHcQ4wXH9Ow95WHHxjRY0jZa0Cs',
    appId: '1:236974689896:ios:b201ab5b4ed0cdb18cf5dd',
    messagingSenderId: '236974689896',
    projectId: 'product-mate',
    storageBucket: 'product-mate.appspot.com',
    iosBundleId: 'com.example.productmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMsqKIgHcQ4wXH9Ow95WHHxjRY0jZa0Cs',
    appId: '1:236974689896:ios:2c1e0991519d5af98cf5dd',
    messagingSenderId: '236974689896',
    projectId: 'product-mate',
    storageBucket: 'product-mate.appspot.com',
    iosBundleId: 'com.example.productmate.RunnerTests',
  );
}
